# Generated by Django 4.0.4 on 2022-05-11 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='date_hired',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 11, 19, 53, 11, 734460)),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='email',
            field=models.BooleanField(max_length=255),
        ),
    ]
