# Generated by Django 4.0.4 on 2022-05-11 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realtors', '0002_alter_realtor_date_hired_alter_realtor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='date_hired',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 11, 20, 1, 45, 401055)),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
