# Generated by Django 4.0.4 on 2022-05-17 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realtors', '0005_alter_realtor_date_hired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='date_hired',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 17, 22, 33, 52, 246843)),
        ),
    ]
